apiVersion: v1
kind: Secret
metadata:
  name: mega-pos-secrets
  namespace: mega-pos
type: Opaque
stringData:
  # Database connection details (separate variables for TypeORM)
  DB_HOST: "mega-pos-db.crowkq8ykqeo.eu-central-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_USERNAME: "megapos_user"
  DB_PASSWORD: "CHANGE_ME"
  DB_DATABASE: "megapos"
  # Other services
  REDIS_URL: "redis://master.shared-redis.uld2os.euc1.cache.amazonaws.com:6379"
  JWT_SECRET: "CHANGE_ME_64_CHAR_RANDOM_STRING"
  NODE_ENV: "production"
