apiVersion: v1
kind: ServiceAccount
metadata:
  name: mega-pos-api
  namespace: mega-pos
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::986906625644:role/hsd-monitoring-mega-pos-mega-pos-api
