apiVersion: v1
kind: ConfigMap
metadata:
  name: pixpos-config
  namespace: pixpos
data:
  NODE_ENV: "production"
  PORT: "3000"
  DATABASE_HOST: "mega-pos-db.crowkq8ykqeo.eu-central-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "megapos"
  DATABASE_USER: "megapos_user"
  CORS_ORIGINS: "https://pos.pixpos.cloud,https://os.pixpos.cloud,https://kitchen.pixpos.cloud,https://waiter.pixpos.cloud,https://queen.pixpos.site,https://pixpos.site"
