apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pixpos-ingress
  namespace: pixpos
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:eu-central-1:986906625644:certificate/e81e9bc7-53b5-41c3-b11a-1bdbee3814a4
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}]'
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
    alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
    alb.ingress.kubernetes.io/healthy-threshold-count: '2'
    alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'
spec:
  rules:
  - host: api.pixpos.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pixpos-api
            port:
              number: 80
