apiVersion: v1
kind: Secret
metadata:
  name: pixpos-secrets
  namespace: pixpos
type: Opaque
stringData:
  DATABASE_PASSWORD: "I66}emTdPl4Bm3Xv?(7E{JIkPbWUy:q_"
  JWT_SECRET: "gERA1TYg7w3OAynB25WYox9Hw8oq44j39SpODiPI"
